/*
 * Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
 * See LICENSE in the project root for license information.
 */

/* global console, document, Excel, Office */

/**
 * Initializes the Office Add-in once the Office JavaScript API is ready.
 * Hides the sideload message, reveals the task pane body, and wires up
 * the "Calculate Maturity" button to the `run` function.
 */
Office.onReady(info => {
  if (info.host === Office.HostType.Excel) {
    document.getElementById("sideload-msg").style.display = "none";
    document.getElementById("app-body").style.display = "flex";
    document.getElementById("run").onclick = run;
  }
});

/**
 * Main entry point triggered when the user clicks "Calculate Maturity".
 *
 * High-level flow:
 *  1. Shows a modal wait spinner while processing.
 *  2. Reads survey responses from the "Form1" sheet / "Table1" table.
 *  3. Deletes any previously generated result sheets (keeps "Form1" and
 *     system sheets whose names start with "_").
 *  4. Computes Level 1 / 2 / 3 weighted maturity scores for every project row.
 *  5. Creates a "DEMaturitySummary" sheet with a one-row-per-project overview.
 *  6. Creates one detail sheet per project showing per-question results.
 *  7. Applies column filters so only non-passing responses are visible.
 *  8. Adds navigation hyperlinks between the summary sheet and each project sheet.
 *  9. Activates the summary sheet and closes the wait spinner.
 *
 * @returns {Promise<void>}
 */
export async function run() {
  try {
    var platform = Office.context.platform;

    // Enable verbose error messages from the Office JS runtime to aid debugging.
    OfficeExtension.config.extendedErrorLogging = true;

    // Show a modal "processing" spinner so the user knows work is in progress.
    Wait.Show("Processing Project Responses", false, function() {});

    await Excel.run(async context => {

      // ─── Maturity Level Question Index Mapping ────────────────────────────
      // Each array contains the column indexes (0-based) in Table1 that belong
      // to the respective maturity level. The indexes match the survey question
      // positions in the header row of the "Form1" sheet.
      //
      //  Level 1 – foundational practices (weighted 70 % of the final score)
      //  Level 2 – intermediate practices (weighted 20 % of the final score)
      //  Level 3 – advanced practices    (weighted 10 % of the final score)
      var level1MaturityIndexes = [7, 8, 9, 10, 11, 12, 13, 14, 18, 19, 20, 21, 22, 23, 24, 27, 28, 29, 30, 31, 33, 34, 35, 36, 37, 38, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 59, 60, 61, 62, 63, 64, 67, 68, 72, 73, 74, 75, 76, 79, 80, 81, 82, 83, 84, 85, 86];
      var level2MaturityIndexes = [15, 16, 25, 17, 32, 39, 55, 56, 57, 65, 66, 69, 77, 87, 88];
      var level3MaturityIndexes = [26, 40, 41, 42, 43, 58, 70, 71, 78, 89, 90, 91];

      // Maximum score a single response can contribute.
      const RESPONSE_MAX_SCORE = 10;

      // Minimum weighted Level 1 score (out of 70) required to avoid being
      // flagged in red on the summary sheet.
      const LEVEL_MIN_THRESHOLD = 70;

      // ─── Response Score Mapping ───────────────────────────────────────────
      // Maps each possible survey answer to its numeric score (0–10).
      // "NA" / "Always" / "Yes" are full-credit answers (10 points).
      // "Frequently" earns partial credit (7 points).
      // "Sometimes" earns minimal credit (4 points).
      // "Never" / "No" / "Don't Know" earn no credit (0 points).
      var responseScores = {};
      responseScores["NA"] = 10;
      responseScores["Always"] = 10;
      responseScores["Frequently"] = 7;
      responseScores["Sometimes"] = 4;
      responseScores["Never"] = 0;
      responseScores["Yes"] = 10;
      responseScores["No"] = 0;
      responseScores["Don't Know"] = 0;

      // ─── Load Workbook Data ───────────────────────────────────────────────
      // Queue requests to load all worksheet names and the survey data from
      // "Form1 / Table1" before the first context.sync() call.
      var sheets = context.workbook.worksheets;
      sheets.load("items/name");

      var mainSheet = context.workbook.worksheets.getItem("Form1");
      var responsesTable = mainSheet.tables.getItem("Table1");

      // Header row holds the survey question text for each column.
      var questions = responsesTable.getHeaderRowRange().load("values");

      // Data body rows hold one survey submission per row.
      var projectResponses = responsesTable.getDataBodyRange().load("values");

      // Execute all queued load requests in a single round-trip to the host.
      await context.sync();

      // ─── Clean Up Previous Results ────────────────────────────────────────
      // Remove all sheets that were generated by a previous run so the add-in
      // can produce a fresh set of results. "Form1" (the source data sheet) and
      // any sheet whose name starts with "_" (Excel internal sheets) are kept.
      for (var i = 0; i < sheets.items.length; i++) {
        if (sheets.items[i].name != "Form1" && !sheets.items[i].name.startsWith("_")) {
          sheets.items[i].delete();
        }
      }
      await context.sync();

      // ─── Build Per-Level Question Dictionaries ────────────────────────────
      // Extract the question text for each maturity level into dictionaries
      // keyed by column index so they can be looked up efficiently later.
      var headerValues = questions.values;
      var level1Questions = getQuestions(headerValues, level1MaturityIndexes);
      var level2Questions = getQuestions(headerValues, level2MaturityIndexes);
      var level3Questions = getQuestions(headerValues, level3MaturityIndexes);

      // ─── Create DEMaturitySummary Sheet ───────────────────────────────────
      // This sheet gives a bird's-eye view of all projects with their weighted
      // scores and final maturity classification.
      var maturitySheet = sheets.add("DEMaturitySummary");
      await context.sync();
      maturitySheet = context.workbook.worksheets.getItem("DEMaturitySummary");
      var summaryTable = maturitySheet.tables.add("A1:J1", true /*hasHeaders*/);
      summaryTable.name = "SummaryTable";
      summaryTable.getHeaderRowRange().values = [["ID", "PROJECT", "REVIEW DATE", "EMAIL", "RESOURCE COUNT", "LEVEL 1 SCORE", "LEVEL 2 SCORE", "LEVEL 3 SCORE", "FINAL SCORE", "MATURITY"]];

      // Accumulate each project's computed data so detail sheets can be
      // populated in a second pass (required due to context.sync ordering).
      var projectSheetsData = [];

      // ─── First Pass: Score Each Project Row ───────────────────────────────
      for (var i = 0; i < projectResponses.values.length; i++) {

        // Calculate the weighted score for each maturity level.
        // Weightages: Level 1 = 70 %, Level 2 = 20 %, Level 3 = 10 %.
        var level1CalculationDetails = CalculateLevelScore(projectResponses.values[i], responseScores, level1MaturityIndexes, 70);
        var level2CalculationDetails = CalculateLevelScore(projectResponses.values[i], responseScores, level2MaturityIndexes, 20);
        var level3CalculationDetails = CalculateLevelScore(projectResponses.values[i], responseScores, level3MaturityIndexes, 10);

        // The final score is the sum of all three weighted level scores (max 100).
        var finalScore = level1CalculationDetails.weightedLevelScore + level2CalculationDetails.weightedLevelScore + level3CalculationDetails.weightedLevelScore;

        // Extract project metadata from the survey row.
        var responseId = projectResponses.values[i][0];
        var projectName = projectResponses.values[i][5];
        var reviewDate = getJsDateFromExcel(projectResponses.values[i][2]);
        var email = projectResponses.values[i][3];
        var resourceCount = projectResponses.values[i][6];

        // Build a safe Excel sheet name: keep only alphanumeric characters,
        // limit to 25 chars, and append the response ID to ensure uniqueness.
        var projectSheetName = projectName.substring(0, 25).replace(/[^a-zA-Z0-9]/g, '') + "_" + responseId;

        // ─── Maturity Classification ─────────────────────────────────────
        // M1 – Foundational  : finalScore ≤ 70
        // M2 – Intermediate  : 70 < finalScore ≤ 90
        // M3 – Advanced      : finalScore > 90
        var maturity = "";
        if (finalScore <= 70) {
          maturity = "M1";
        }
        else if (finalScore > 70 && finalScore <= 90) {
          maturity = "M2";
        }
        else if (finalScore > 90) {
          maturity = "M3";
        }

        // Append a row to the summary table for this project.
        summaryTable.rows.add(null,
          [[responseId,
            projectName,
            reviewDate,
            email,
            resourceCount,
            level1CalculationDetails.weightedLevelScore,
            level2CalculationDetails.weightedLevelScore,
            level3CalculationDetails.weightedLevelScore,
            finalScore,
            maturity
          ]]
        );

        // Highlight the Level 1 score in red when it falls below the minimum
        // threshold (70), indicating the project has not met basic practices.
        if (level1CalculationDetails.weightedLevelScore < LEVEL_MIN_THRESHOLD) {
          summaryTable.rows.getItemAt(i).getRange().getCell(0, 5).format.font.color = "#FF0000";
        }

        // Add the individual project sheet now (before context.sync) so all
        // sheet creation calls are batched in the same sync round-trip.
        sheets.add(projectSheetName);

        // Store all calculated data for the second pass that writes detail sheets.
        projectSheetsData.push(
          {
            Id: responseId,
            projectName: projectName,
            email: email,
            reviewDate: reviewDate,
            resourceCount: resourceCount,
            level1CalculationDetails: level1CalculationDetails,
            level2CalculationDetails: level2CalculationDetails,
            level3CalculationDetails: level3CalculationDetails,
            finalScore: finalScore,
            maturity: maturity,
            projectSheetName: projectSheetName
          }
        );
      }

      // Auto-size columns and rows on the summary sheet for readability.
      if (Office.context.requirements.isSetSupported("ExcelApi", "1.2")) {
        maturitySheet.getUsedRange().format.autofitColumns();
        maturitySheet.getUsedRange().format.autofitRows();
      }

      // Commit all sheet additions and summary table rows to the workbook.
      await context.sync();

      // ─── Second Pass: Populate Individual Project Detail Sheets ──────────
      for (var i = 0; i < projectSheetsData.length; i++) {
        var projectSheetData = projectSheetsData[i];
        var projectSheet = sheets.getItem(projectSheetData.projectSheetName);

        // Write a two-column summary block (A1:B10) at the top of the sheet
        // so reviewers can see key metrics at a glance.
        var summaryData = [
          ["ID", projectSheetData.Id],
          ["PROJECT", projectSheetData.projectName],
          ["REVIEW DATE", projectSheetData.reviewDate],
          ["EMAIL", projectSheetData.email],
          ["RESOURCE COUNT", projectSheetData.resourceCount],
          ["LEVEL 1 SCORE", projectSheetData.level1CalculationDetails.weightedLevelScore],
          ["LEVEL 2 SCORE", projectSheetData.level2CalculationDetails.weightedLevelScore],
          ["LEVEL 3 SCORE", projectSheetData.level3CalculationDetails.weightedLevelScore],
          ["FINAL SCORE", projectSheetData.finalScore],
          ["MATURITY", projectSheetData.maturity]
        ];
        var summaryRange = projectSheet.getRange("A1:B10");
        summaryRange.values = summaryData;
        if (Office.context.requirements.isSetSupported("ExcelApi", "1.2")) {
          summaryRange.format.autofitColumns();
        }

        // Highlight the Level 1 score cell in red if the project is below
        // the minimum threshold, drawing immediate attention to the gap.
        if (projectSheetData.level1CalculationDetails.weightedLevelScore < 70) {
          var level1ScoreRange = summaryRange.getCell(5, 1); // row 5 = "LEVEL 1 SCORE", col 1 = value
          level1ScoreRange.format.font.color = "#FF0000";
        }

        // Style the Maturity cell (B10) with a distinctive look: light yellow
        // background, dark maroon bold text, and a double border on all sides.
        var maturityCellRange = summaryRange.getCell(9, 1); // row 9 = "MATURITY", col 1 = value
        maturityCellRange.format.fill.color = "#FFFFE0";
        maturityCellRange.format.horizontalAlignment = "Center";
        maturityCellRange.format.borders.getItem('InsideHorizontal').style = "Double";
        maturityCellRange.format.borders.getItem('InsideVertical').style = "Double";
        maturityCellRange.format.borders.getItem('EdgeBottom').style = "Double";
        maturityCellRange.format.borders.getItem('EdgeLeft').style = "Double";
        maturityCellRange.format.borders.getItem('EdgeRight').style = "Double";
        maturityCellRange.format.borders.getItem('EdgeTop').style = "Double";
        maturityCellRange.format.font.bold = true;
        maturityCellRange.format.font.color = "#800000";

        // ─── Level Question Tables ──────────────────────────────────────
        // Each level gets a header label row followed by a two-column table
        // (Question | Response). Rows with non-passing responses are shown
        // in red text so reviewers can immediately identify gaps.

        // Level 1 Questions table starts at row 14 (rows 1–10 = summary,
        // row 11 = back-link, rows 12–13 = spacer).
        var rowIndex = 14;
        projectSheet.getRange("B" + (rowIndex - 1)).values = [["Level 1 Questions"]];
        var level1Range = projectSheet.getRange("B" + (rowIndex - 1) + ":" + "C" + (rowIndex - 1));
        applyLevelQuestionTopRowProperties(level1Range);

        rowIndex = addLevelTable(level1Questions,
          projectSheetData.level1CalculationDetails.levelFailures,
          projectSheet,
          level1MaturityIndexes,
          "Level1",
          projectResponses.values[i],
          rowIndex,
          context);

        // Level 2 Questions table follows Level 1 with a 3-row gap.
        projectSheet.getRange("B" + (rowIndex + 3)).values = [["Level 2 Questions"]];
        var level2Range = projectSheet.getRange("B" + (rowIndex + 3) + ":" + "C" + (rowIndex + 3));
        applyLevelQuestionTopRowProperties(level2Range);

        rowIndex = addLevelTable(level2Questions,
          projectSheetData.level2CalculationDetails.levelFailures,
          projectSheet,
          level2MaturityIndexes,
          "Level2",
          projectResponses.values[i],
          rowIndex + 4,
          context);

        // Level 3 Questions table follows Level 2 with a 3-row gap.
        projectSheet.getRange("B" + (rowIndex + 3)).values = [["Level 3 Questions"]];
        var level3Range = projectSheet.getRange("B" + (rowIndex + 3) + ":" + "C" + (rowIndex + 3));
        applyLevelQuestionTopRowProperties(level3Range);

        rowIndex = addLevelTable(level3Questions,
          projectSheetData.level3CalculationDetails.levelFailures,
          projectSheet,
          level3MaturityIndexes,
          "Level3",
          projectResponses.values[i],
          rowIndex + 4,
          context);

        // Auto-size all columns and rows on the detail sheet for readability.
        if (Office.context.requirements.isSetSupported("ExcelApi", "1.2")) {
          projectSheet.getUsedRange().format.autofitColumns();
          projectSheet.getUsedRange().format.autofitRows();
        }

        // Office Online does not support awaiting context.sync inside a loop,
        // so we use a fire-and-forget sync there and await it on desktop.
        if (platform == "OfficeOnline") {
          context.sync();
        }
        else {
          await context.sync();
        }
      }

      // ─── Third Pass: Apply Filters and Hyperlinks ─────────────────────────
      // Now that all detail sheets are fully written we can:
      //  • Filter each level table so only non-passing responses are visible,
      //    making it easy to spot deficiencies at a glance.
      //  • Add clickable hyperlinks between the summary sheet and each project
      //    sheet for easy navigation.
      summaryTable = maturitySheet.tables.getItem("SummaryTable");
      for (var i = 0; i < projectSheetsData.length; i++) {
        var projectSheetData = projectSheetsData[i];
        var projectSheet = sheets.getItem(projectSheetsData[i].projectSheetName);

        // Apply response filters to each level's question table.
        // Only rows where the answer is not "Always", "Yes", or "NA" remain visible.
        var level1filter = projectSheet.tables.getItem("Level1Table" + projectResponses.values[i][0]).columns.getItem("Response").filter;
        applyFilter(level1filter);
        var level2filter = projectSheet.tables.getItem("Level2Table" + projectResponses.values[i][0]).columns.getItem("Response").filter;
        applyFilter(level2filter);
        var level3filter = projectSheet.tables.getItem("Level3Table" + projectResponses.values[i][0]).columns.getItem("Response").filter;
        applyFilter(level3filter);

        // Add a hyperlink in the summary sheet's PROJECT column (column B)
        // that navigates directly to the corresponding project detail sheet.
        var gotoProjectLink = {
          textToDisplay: projectResponses.values[i][5],
          screenTip: "Navigate to the " + projectResponses.values[i][5] + " worksheet",
          documentReference: projectSheetsData[i].projectSheetName + "!A2"
        };
        var projecthyperRange = maturitySheet.getRange("B" + (i + 2));
        projecthyperRange.getCell(0, 0).hyperlink = gotoProjectLink;

        // Add a hyperlink in the summary sheet's MATURITY column (column J)
        // that navigates to the maturity cell (B10) on the project detail sheet.
        var gotoProjectLinkFromMaturity = {
          textToDisplay: projectSheetData.maturity,
          screenTip: "Navigate to the " + projectResponses.values[i][5] + " worksheet",
          documentReference: projectSheetsData[i].projectSheetName + "!B10"
        };
        var maturityhyperRange = maturitySheet.getRange("J" + (i + 2));
        maturityhyperRange.getCell(0, 0).hyperlink = gotoProjectLinkFromMaturity;

        // Style the maturity hyperlink cell to match the maturity cell on the
        // detail sheet (light yellow background, bold dark maroon text).
        maturityhyperRange.format.fill.color = "#FFFFE0";
        maturityhyperRange.format.font.bold = true;
        maturityhyperRange.format.font.color = "#800000";

        // Add a "back" hyperlink in cell B11 of each project detail sheet
        // that navigates back to the DEMaturitySummary sheet (cell A1).
        var gotoSummaryLink = {
          textToDisplay: "Click here to go to DEMaturitySummary sheet",
          screenTip: "Navigate to the DEMaturitySummary worksheet",
          documentReference: "DEMaturitySummary" + "!A1"
        };
        var hyperlinkRange = projectSheet.getRange("B11");
        hyperlinkRange.getCell(0, 0).hyperlink = gotoSummaryLink;
        hyperlinkRange.format.font.bold = true;
        hyperlinkRange.format.font.color = "#7C3606";
        hyperlinkRange.format.horizontalAlignment = "Center";
        hyperlinkRange.format.fill.color = "#E1D70F";

        context.sync();
      }

      // Bring the summary sheet into focus once all processing is complete.
      maturitySheet.activate();
      await context.sync();


      // ─── Helper Functions ─────────────────────────────────────────────────

      /**
       * Builds a dictionary that maps column index → question text for a given
       * set of maturity-level question indexes.
       *
       * @param {any[][]} questionsRow  - The 2-D values array from the header row
       *                                  (first element is the actual header array).
       * @param {number[]} levelIndexes - Column indexes belonging to this level.
       * @returns {{ [index: number]: string }} Dictionary of index → question text.
       */
      function getQuestions(questionsRow, levelIndexes) {
        var questionDictionary = {};
        levelIndexes.forEach(element => {
          questionDictionary[element] = questionsRow[0][element];
        });
        return questionDictionary;
      }

      /**
       * Calculates the weighted maturity score for a single project row at
       * one maturity level.
       *
       * Algorithm:
       *  1. For each question column in `levelIndexes`, look up the project's
       *     answer in `responseScores` to obtain a numeric score (0–10).
       *  2. Sum all individual scores → `levelScore`.
       *  3. Express as a percentage of the maximum possible score
       *     (`levelIndexes.length × 10`).
       *  4. Multiply the percentage by the level's `weightage` to get the
       *     contribution to the overall 100-point final score.
       *
       * @param {any[]}              projectRow     - All column values for one survey row.
       * @param {{ [key: string]: number }} responseScores - Map of answer → numeric score.
       * @param {number[]}           levelIndexes   - Column indexes for this level's questions.
       * @param {number}             weightage      - Weight of this level (70, 20, or 10).
       * @returns {{
       *   levelFailures: { [index: number]: number },
       *   unWeightedLevelScore: number,
       *   unWeightedLevelPercentage: number,
       *   weightedLevelScore: number
       * }}
       */
      function CalculateLevelScore(projectRow, responseScores, levelIndexes, weightage) {
        var levelFailures = {};   // Tracks indexes of questions that did not score full marks.
        var levelScore = 0.0;
        var maxLevelScore = levelIndexes.length * 10; // Maximum achievable score for this level.
        var levelscorearr = [];   // Individual question scores (kept for potential future use).

        levelIndexes.forEach(element => {
          var response = projectRow[element];
          if (response && responseScores[response] !== undefined) {
            var score = parseFloat(responseScores[response]);

            // Record this question index as a failure if it didn't achieve the
            // maximum possible score (i.e. any answer other than "Always"/"Yes"/"NA").
            if (score != RESPONSE_MAX_SCORE) {
              levelFailures[element] = element;
            }
            levelscorearr.push(score);
            levelScore = levelScore + score;
          }
          else {
            // Missing or unrecognised responses contribute 0 to the level score.
            levelScore = levelScore + 0;
          }
        });

        // Convert the raw score to a percentage of the maximum achievable score,
        // then apply the level's weight to get the final weighted contribution.
        var levelpercentage = (levelScore * 100) / maxLevelScore;
        var weightedLevelScore = ((levelpercentage * weightage) / 100).toFixed(2);

        return {
          levelFailures: levelFailures,
          unWeightedLevelScore: levelScore,
          unWeightedLevelPercentage: levelpercentage,
          weightedLevelScore: parseFloat(weightedLevelScore)
        };
      }

      /**
       * Applies a value-based column filter to a table's "Response" column so
       * that only non-passing answers remain visible. This allows reviewers to
       * focus on the areas that need improvement.
       *
       * Non-passing response values: "Frequently", "Sometimes", "Never", "No",
       * and "Don't Know".
       *
       * @param {Excel.Filter} filter - The filter object for the "Response" column.
       */
      function applyFilter(filter) {
        filter.apply({
          filterOn: Excel.FilterOn.values,
          values: ["Frequently", "Sometimes", "Never", "No", "Don't Know"]
        });
      }

      /**
       * Converts an Excel date serial number to a human-readable date string
       * in MM-DD-YYYY format.
       *
       * Excel stores dates as the number of days since 1 January 1900 (with a
       * known leap-year bug that adds 2 extra days).  This function subtracts
       * the offset (25567 + 2) to get the Unix epoch equivalent, then converts
       * to milliseconds and constructs a JavaScript Date.
       *
       * @param {number} dateValue - Excel date serial number (e.g. 44927 for 2023-01-01).
       * @returns {string} Formatted date string in MM-DD-YYYY format.
       */
      function getJsDateFromExcel(dateValue) {
        // Subtract the Excel-to-Unix epoch offset and multiply to get milliseconds.
        var reviewDate = new Date((dateValue - (25567 + 2)) * 86400 * 1000);

        let dd = reviewDate.getDate();
        let mm = reviewDate.getMonth() + 1; // getMonth() is 0-based; add 1 for human-readable month.
        const yyyy = reviewDate.getFullYear();

        // Zero-pad single-digit day and month values.
        if (dd < 10) { dd = `0${dd}`; }
        if (mm < 10) { mm = `0${mm}`; }

        return reviewDate = `${mm}-${dd}-${yyyy}`;
      }

      /**
       * Creates a two-column Excel table (Question | Response) on a project
       * detail sheet for one maturity level, then highlights rows whose
       * responses did not achieve the maximum score.
       *
       * @param {{ [index: number]: string }} questions      - Map of column index → question text.
       * @param {{ [index: number]: number }} levelFailures  - Map of column indexes that failed.
       * @param {Excel.Worksheet}             projectSheet   - Target worksheet.
       * @param {number[]}                    levelIndexes   - Ordered column indexes for this level.
       * @param {string}                      level          - Level name prefix, e.g. "Level1".
       * @param {any[]}                       projectResponse - All column values for the project row.
       * @param {number}                      rowIndex       - Starting row (1-based) for the table.
       * @param {Excel.RequestContext}        context        - Excel request context (unused directly
       *                                                       but kept for future sync flexibility).
       * @returns {number} The next available row index after the table's last data row.
       */
      function addLevelTable(questions, levelFailures, projectSheet, levelIndexes, level, projectResponse, rowIndex, context) {
        var tabeleRange = "B" + rowIndex + ":" + "C" + rowIndex;
        var levelQuestionsTable = projectSheet.tables.add(tabeleRange, true /*hasHeaders*/);

        // Name the table using level + "Table" + responseId to ensure uniqueness
        // across multiple project sheets (e.g. "Level1Table42").
        levelQuestionsTable.name = level + "Table" + projectResponse[0];
        levelQuestionsTable.getHeaderRowRange().values = [["Question", "Response"]];
        levelQuestionsTable.getDataBodyRange().format.font.color = "#000000";

        levelIndexes.forEach(function (levelIndex, index) {
          // Add one row per question containing the question text and the
          // project's answer for that question column.
          levelQuestionsTable.rows.add(null, [[
            questions[levelIndex],
            projectResponse[levelIndex]
          ]]);

          // Highlight the entire row in red if the response did not achieve
          // the maximum score (i.e. the index exists in levelFailures).
          if (levelFailures[levelIndex] !== undefined) {
            levelQuestionsTable.rows.getItemAt(index).getRange().format.font.color = "#FF0000";
          }
          rowIndex++;
        });

        return rowIndex;
      }

      /**
       * Applies consistent header-row formatting to the merged label cell above
       * each level's question table: bold white text centered on a blue background.
       *
       * @param {Excel.Range} levelRange - The merged range containing the level label
       *                                   (e.g. "B13:C13" for "Level 1 Questions").
       */
      function applyLevelQuestionTopRowProperties(levelRange) {
        levelRange.merge = true;
        levelRange.format.font.bold = true;
        levelRange.format.font.color = "#FFFFFF";
        levelRange.format.horizontalAlignment = "Center";
        levelRange.format.fill.color = "#154CC5";
      }

    }).catch(function(error){
      console.error(error);

      // Provide a user-friendly error message; specialise the text for the most
      // common error case where the add-in is not run against a DE Survey workbook.
      var errormessage = "There is an error in processing project responses. Please try again or later";
      if (error.code == "ItemNotFound") {
        errormessage = "Please run add-in on DE Survey responses";
      }

      // Close the wait spinner before showing the error dialog so they don't overlap.
      Wait.CloseDialogAsync(function() {
        MessageBox.Show(errormessage,
          "Error",
          MessageBoxButtons.OkOnly,
          MessageBoxIcons.Error,
          false,
          null,
          function(buttonfirst){
            MessageBox.CloseDialogAsync(function(){});
          },
          false
        );
      });
    });

    // Dismiss the wait spinner if it is still showing after Excel.run completes.
    if (Wait.Displayed()) {
      Wait.CloseDialogAsync(function () { });
    }
  } catch (error) {
    console.error(error);
  }
}
